apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-deploy
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 6
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node-app
          image: pinrojas/hello-node:v1
          ports:
            - containerPort: 8080
              protocol: TCP
